name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set CGO_CFLAGS
        run: export CGO_CFLAGS="-O2 -Wno-stringop-overread"

      - name: Build
        run: go build -ldflags "-w -s" -o ./PixelBot .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-build
          path: ./PixelBot
